# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_CIntegrateAndFireTransferFunction', [dirname(__file__)])
        except ImportError:
            import _CIntegrateAndFireTransferFunction
            return _CIntegrateAndFireTransferFunction
        if fp is not None:
            try:
                _mod = imp.load_module('_CIntegrateAndFireTransferFunction', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _CIntegrateAndFireTransferFunction = swig_import_helper()
    del swig_import_helper
else:
    import _CIntegrateAndFireTransferFunction
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _CIntegrateAndFireTransferFunction.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _CIntegrateAndFireTransferFunction.SwigPyIterator_value(self)
    def incr(self, n=1): return _CIntegrateAndFireTransferFunction.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _CIntegrateAndFireTransferFunction.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _CIntegrateAndFireTransferFunction.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _CIntegrateAndFireTransferFunction.SwigPyIterator_equal(self, *args)
    def copy(self): return _CIntegrateAndFireTransferFunction.SwigPyIterator_copy(self)
    def next(self): return _CIntegrateAndFireTransferFunction.SwigPyIterator_next(self)
    def __next__(self): return _CIntegrateAndFireTransferFunction.SwigPyIterator___next__(self)
    def previous(self): return _CIntegrateAndFireTransferFunction.SwigPyIterator_previous(self)
    def advance(self, *args): return _CIntegrateAndFireTransferFunction.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _CIntegrateAndFireTransferFunction.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _CIntegrateAndFireTransferFunction.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _CIntegrateAndFireTransferFunction.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _CIntegrateAndFireTransferFunction.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _CIntegrateAndFireTransferFunction.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _CIntegrateAndFireTransferFunction.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _CIntegrateAndFireTransferFunction.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _CIntegrateAndFireTransferFunction.IntVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _CIntegrateAndFireTransferFunction.IntVector___nonzero__(self)
    def __bool__(self): return _CIntegrateAndFireTransferFunction.IntVector___bool__(self)
    def __len__(self): return _CIntegrateAndFireTransferFunction.IntVector___len__(self)
    def pop(self): return _CIntegrateAndFireTransferFunction.IntVector_pop(self)
    def __getslice__(self, *args): return _CIntegrateAndFireTransferFunction.IntVector___getslice__(self, *args)
    def __setslice__(self, *args): return _CIntegrateAndFireTransferFunction.IntVector___setslice__(self, *args)
    def __delslice__(self, *args): return _CIntegrateAndFireTransferFunction.IntVector___delslice__(self, *args)
    def __delitem__(self, *args): return _CIntegrateAndFireTransferFunction.IntVector___delitem__(self, *args)
    def __getitem__(self, *args): return _CIntegrateAndFireTransferFunction.IntVector___getitem__(self, *args)
    def __setitem__(self, *args): return _CIntegrateAndFireTransferFunction.IntVector___setitem__(self, *args)
    def append(self, *args): return _CIntegrateAndFireTransferFunction.IntVector_append(self, *args)
    def empty(self): return _CIntegrateAndFireTransferFunction.IntVector_empty(self)
    def size(self): return _CIntegrateAndFireTransferFunction.IntVector_size(self)
    def clear(self): return _CIntegrateAndFireTransferFunction.IntVector_clear(self)
    def swap(self, *args): return _CIntegrateAndFireTransferFunction.IntVector_swap(self, *args)
    def get_allocator(self): return _CIntegrateAndFireTransferFunction.IntVector_get_allocator(self)
    def begin(self): return _CIntegrateAndFireTransferFunction.IntVector_begin(self)
    def end(self): return _CIntegrateAndFireTransferFunction.IntVector_end(self)
    def rbegin(self): return _CIntegrateAndFireTransferFunction.IntVector_rbegin(self)
    def rend(self): return _CIntegrateAndFireTransferFunction.IntVector_rend(self)
    def pop_back(self): return _CIntegrateAndFireTransferFunction.IntVector_pop_back(self)
    def erase(self, *args): return _CIntegrateAndFireTransferFunction.IntVector_erase(self, *args)
    def __init__(self, *args): 
        this = _CIntegrateAndFireTransferFunction.new_IntVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _CIntegrateAndFireTransferFunction.IntVector_push_back(self, *args)
    def front(self): return _CIntegrateAndFireTransferFunction.IntVector_front(self)
    def back(self): return _CIntegrateAndFireTransferFunction.IntVector_back(self)
    def assign(self, *args): return _CIntegrateAndFireTransferFunction.IntVector_assign(self, *args)
    def resize(self, *args): return _CIntegrateAndFireTransferFunction.IntVector_resize(self, *args)
    def insert(self, *args): return _CIntegrateAndFireTransferFunction.IntVector_insert(self, *args)
    def reserve(self, *args): return _CIntegrateAndFireTransferFunction.IntVector_reserve(self, *args)
    def capacity(self): return _CIntegrateAndFireTransferFunction.IntVector_capacity(self)
    __swig_destroy__ = _CIntegrateAndFireTransferFunction.delete_IntVector
    __del__ = lambda self : None;
IntVector_swigregister = _CIntegrateAndFireTransferFunction.IntVector_swigregister
IntVector_swigregister(IntVector)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _CIntegrateAndFireTransferFunction.DoubleVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _CIntegrateAndFireTransferFunction.DoubleVector___nonzero__(self)
    def __bool__(self): return _CIntegrateAndFireTransferFunction.DoubleVector___bool__(self)
    def __len__(self): return _CIntegrateAndFireTransferFunction.DoubleVector___len__(self)
    def pop(self): return _CIntegrateAndFireTransferFunction.DoubleVector_pop(self)
    def __getslice__(self, *args): return _CIntegrateAndFireTransferFunction.DoubleVector___getslice__(self, *args)
    def __setslice__(self, *args): return _CIntegrateAndFireTransferFunction.DoubleVector___setslice__(self, *args)
    def __delslice__(self, *args): return _CIntegrateAndFireTransferFunction.DoubleVector___delslice__(self, *args)
    def __delitem__(self, *args): return _CIntegrateAndFireTransferFunction.DoubleVector___delitem__(self, *args)
    def __getitem__(self, *args): return _CIntegrateAndFireTransferFunction.DoubleVector___getitem__(self, *args)
    def __setitem__(self, *args): return _CIntegrateAndFireTransferFunction.DoubleVector___setitem__(self, *args)
    def append(self, *args): return _CIntegrateAndFireTransferFunction.DoubleVector_append(self, *args)
    def empty(self): return _CIntegrateAndFireTransferFunction.DoubleVector_empty(self)
    def size(self): return _CIntegrateAndFireTransferFunction.DoubleVector_size(self)
    def clear(self): return _CIntegrateAndFireTransferFunction.DoubleVector_clear(self)
    def swap(self, *args): return _CIntegrateAndFireTransferFunction.DoubleVector_swap(self, *args)
    def get_allocator(self): return _CIntegrateAndFireTransferFunction.DoubleVector_get_allocator(self)
    def begin(self): return _CIntegrateAndFireTransferFunction.DoubleVector_begin(self)
    def end(self): return _CIntegrateAndFireTransferFunction.DoubleVector_end(self)
    def rbegin(self): return _CIntegrateAndFireTransferFunction.DoubleVector_rbegin(self)
    def rend(self): return _CIntegrateAndFireTransferFunction.DoubleVector_rend(self)
    def pop_back(self): return _CIntegrateAndFireTransferFunction.DoubleVector_pop_back(self)
    def erase(self, *args): return _CIntegrateAndFireTransferFunction.DoubleVector_erase(self, *args)
    def __init__(self, *args): 
        this = _CIntegrateAndFireTransferFunction.new_DoubleVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _CIntegrateAndFireTransferFunction.DoubleVector_push_back(self, *args)
    def front(self): return _CIntegrateAndFireTransferFunction.DoubleVector_front(self)
    def back(self): return _CIntegrateAndFireTransferFunction.DoubleVector_back(self)
    def assign(self, *args): return _CIntegrateAndFireTransferFunction.DoubleVector_assign(self, *args)
    def resize(self, *args): return _CIntegrateAndFireTransferFunction.DoubleVector_resize(self, *args)
    def insert(self, *args): return _CIntegrateAndFireTransferFunction.DoubleVector_insert(self, *args)
    def reserve(self, *args): return _CIntegrateAndFireTransferFunction.DoubleVector_reserve(self, *args)
    def capacity(self): return _CIntegrateAndFireTransferFunction.DoubleVector_capacity(self)
    __swig_destroy__ = _CIntegrateAndFireTransferFunction.delete_DoubleVector
    __del__ = lambda self : None;
DoubleVector_swigregister = _CIntegrateAndFireTransferFunction.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)

class DoubleVectorVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVectorVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVectorVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _CIntegrateAndFireTransferFunction.DoubleVectorVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _CIntegrateAndFireTransferFunction.DoubleVectorVector___nonzero__(self)
    def __bool__(self): return _CIntegrateAndFireTransferFunction.DoubleVectorVector___bool__(self)
    def __len__(self): return _CIntegrateAndFireTransferFunction.DoubleVectorVector___len__(self)
    def pop(self): return _CIntegrateAndFireTransferFunction.DoubleVectorVector_pop(self)
    def __getslice__(self, *args): return _CIntegrateAndFireTransferFunction.DoubleVectorVector___getslice__(self, *args)
    def __setslice__(self, *args): return _CIntegrateAndFireTransferFunction.DoubleVectorVector___setslice__(self, *args)
    def __delslice__(self, *args): return _CIntegrateAndFireTransferFunction.DoubleVectorVector___delslice__(self, *args)
    def __delitem__(self, *args): return _CIntegrateAndFireTransferFunction.DoubleVectorVector___delitem__(self, *args)
    def __getitem__(self, *args): return _CIntegrateAndFireTransferFunction.DoubleVectorVector___getitem__(self, *args)
    def __setitem__(self, *args): return _CIntegrateAndFireTransferFunction.DoubleVectorVector___setitem__(self, *args)
    def append(self, *args): return _CIntegrateAndFireTransferFunction.DoubleVectorVector_append(self, *args)
    def empty(self): return _CIntegrateAndFireTransferFunction.DoubleVectorVector_empty(self)
    def size(self): return _CIntegrateAndFireTransferFunction.DoubleVectorVector_size(self)
    def clear(self): return _CIntegrateAndFireTransferFunction.DoubleVectorVector_clear(self)
    def swap(self, *args): return _CIntegrateAndFireTransferFunction.DoubleVectorVector_swap(self, *args)
    def get_allocator(self): return _CIntegrateAndFireTransferFunction.DoubleVectorVector_get_allocator(self)
    def begin(self): return _CIntegrateAndFireTransferFunction.DoubleVectorVector_begin(self)
    def end(self): return _CIntegrateAndFireTransferFunction.DoubleVectorVector_end(self)
    def rbegin(self): return _CIntegrateAndFireTransferFunction.DoubleVectorVector_rbegin(self)
    def rend(self): return _CIntegrateAndFireTransferFunction.DoubleVectorVector_rend(self)
    def pop_back(self): return _CIntegrateAndFireTransferFunction.DoubleVectorVector_pop_back(self)
    def erase(self, *args): return _CIntegrateAndFireTransferFunction.DoubleVectorVector_erase(self, *args)
    def __init__(self, *args): 
        this = _CIntegrateAndFireTransferFunction.new_DoubleVectorVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _CIntegrateAndFireTransferFunction.DoubleVectorVector_push_back(self, *args)
    def front(self): return _CIntegrateAndFireTransferFunction.DoubleVectorVector_front(self)
    def back(self): return _CIntegrateAndFireTransferFunction.DoubleVectorVector_back(self)
    def assign(self, *args): return _CIntegrateAndFireTransferFunction.DoubleVectorVector_assign(self, *args)
    def resize(self, *args): return _CIntegrateAndFireTransferFunction.DoubleVectorVector_resize(self, *args)
    def insert(self, *args): return _CIntegrateAndFireTransferFunction.DoubleVectorVector_insert(self, *args)
    def reserve(self, *args): return _CIntegrateAndFireTransferFunction.DoubleVectorVector_reserve(self, *args)
    def capacity(self): return _CIntegrateAndFireTransferFunction.DoubleVectorVector_capacity(self)
    __swig_destroy__ = _CIntegrateAndFireTransferFunction.delete_DoubleVectorVector
    __del__ = lambda self : None;
DoubleVectorVector_swigregister = _CIntegrateAndFireTransferFunction.DoubleVectorVector_swigregister
DoubleVectorVector_swigregister(DoubleVectorVector)

class StringVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _CIntegrateAndFireTransferFunction.StringVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _CIntegrateAndFireTransferFunction.StringVector___nonzero__(self)
    def __bool__(self): return _CIntegrateAndFireTransferFunction.StringVector___bool__(self)
    def __len__(self): return _CIntegrateAndFireTransferFunction.StringVector___len__(self)
    def pop(self): return _CIntegrateAndFireTransferFunction.StringVector_pop(self)
    def __getslice__(self, *args): return _CIntegrateAndFireTransferFunction.StringVector___getslice__(self, *args)
    def __setslice__(self, *args): return _CIntegrateAndFireTransferFunction.StringVector___setslice__(self, *args)
    def __delslice__(self, *args): return _CIntegrateAndFireTransferFunction.StringVector___delslice__(self, *args)
    def __delitem__(self, *args): return _CIntegrateAndFireTransferFunction.StringVector___delitem__(self, *args)
    def __getitem__(self, *args): return _CIntegrateAndFireTransferFunction.StringVector___getitem__(self, *args)
    def __setitem__(self, *args): return _CIntegrateAndFireTransferFunction.StringVector___setitem__(self, *args)
    def append(self, *args): return _CIntegrateAndFireTransferFunction.StringVector_append(self, *args)
    def empty(self): return _CIntegrateAndFireTransferFunction.StringVector_empty(self)
    def size(self): return _CIntegrateAndFireTransferFunction.StringVector_size(self)
    def clear(self): return _CIntegrateAndFireTransferFunction.StringVector_clear(self)
    def swap(self, *args): return _CIntegrateAndFireTransferFunction.StringVector_swap(self, *args)
    def get_allocator(self): return _CIntegrateAndFireTransferFunction.StringVector_get_allocator(self)
    def begin(self): return _CIntegrateAndFireTransferFunction.StringVector_begin(self)
    def end(self): return _CIntegrateAndFireTransferFunction.StringVector_end(self)
    def rbegin(self): return _CIntegrateAndFireTransferFunction.StringVector_rbegin(self)
    def rend(self): return _CIntegrateAndFireTransferFunction.StringVector_rend(self)
    def pop_back(self): return _CIntegrateAndFireTransferFunction.StringVector_pop_back(self)
    def erase(self, *args): return _CIntegrateAndFireTransferFunction.StringVector_erase(self, *args)
    def __init__(self, *args): 
        this = _CIntegrateAndFireTransferFunction.new_StringVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _CIntegrateAndFireTransferFunction.StringVector_push_back(self, *args)
    def front(self): return _CIntegrateAndFireTransferFunction.StringVector_front(self)
    def back(self): return _CIntegrateAndFireTransferFunction.StringVector_back(self)
    def assign(self, *args): return _CIntegrateAndFireTransferFunction.StringVector_assign(self, *args)
    def resize(self, *args): return _CIntegrateAndFireTransferFunction.StringVector_resize(self, *args)
    def insert(self, *args): return _CIntegrateAndFireTransferFunction.StringVector_insert(self, *args)
    def reserve(self, *args): return _CIntegrateAndFireTransferFunction.StringVector_reserve(self, *args)
    def capacity(self): return _CIntegrateAndFireTransferFunction.StringVector_capacity(self)
    __swig_destroy__ = _CIntegrateAndFireTransferFunction.delete_StringVector
    __del__ = lambda self : None;
StringVector_swigregister = _CIntegrateAndFireTransferFunction.StringVector_swigregister
StringVector_swigregister(StringVector)

class MapStringInt(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MapStringInt, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MapStringInt, name)
    __repr__ = _swig_repr
    def iterator(self): return _CIntegrateAndFireTransferFunction.MapStringInt_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _CIntegrateAndFireTransferFunction.MapStringInt___nonzero__(self)
    def __bool__(self): return _CIntegrateAndFireTransferFunction.MapStringInt___bool__(self)
    def __len__(self): return _CIntegrateAndFireTransferFunction.MapStringInt___len__(self)
    def __iter__(self): return self.key_iterator()
    def iterkeys(self): return self.key_iterator()
    def itervalues(self): return self.value_iterator()
    def iteritems(self): return self.iterator()
    def __getitem__(self, *args): return _CIntegrateAndFireTransferFunction.MapStringInt___getitem__(self, *args)
    def __delitem__(self, *args): return _CIntegrateAndFireTransferFunction.MapStringInt___delitem__(self, *args)
    def has_key(self, *args): return _CIntegrateAndFireTransferFunction.MapStringInt_has_key(self, *args)
    def keys(self): return _CIntegrateAndFireTransferFunction.MapStringInt_keys(self)
    def values(self): return _CIntegrateAndFireTransferFunction.MapStringInt_values(self)
    def items(self): return _CIntegrateAndFireTransferFunction.MapStringInt_items(self)
    def __contains__(self, *args): return _CIntegrateAndFireTransferFunction.MapStringInt___contains__(self, *args)
    def key_iterator(self): return _CIntegrateAndFireTransferFunction.MapStringInt_key_iterator(self)
    def value_iterator(self): return _CIntegrateAndFireTransferFunction.MapStringInt_value_iterator(self)
    def __setitem__(self, *args): return _CIntegrateAndFireTransferFunction.MapStringInt___setitem__(self, *args)
    def asdict(self): return _CIntegrateAndFireTransferFunction.MapStringInt_asdict(self)
    def __init__(self, *args): 
        this = _CIntegrateAndFireTransferFunction.new_MapStringInt(*args)
        try: self.this.append(this)
        except: self.this = this
    def empty(self): return _CIntegrateAndFireTransferFunction.MapStringInt_empty(self)
    def size(self): return _CIntegrateAndFireTransferFunction.MapStringInt_size(self)
    def clear(self): return _CIntegrateAndFireTransferFunction.MapStringInt_clear(self)
    def swap(self, *args): return _CIntegrateAndFireTransferFunction.MapStringInt_swap(self, *args)
    def get_allocator(self): return _CIntegrateAndFireTransferFunction.MapStringInt_get_allocator(self)
    def begin(self): return _CIntegrateAndFireTransferFunction.MapStringInt_begin(self)
    def end(self): return _CIntegrateAndFireTransferFunction.MapStringInt_end(self)
    def rbegin(self): return _CIntegrateAndFireTransferFunction.MapStringInt_rbegin(self)
    def rend(self): return _CIntegrateAndFireTransferFunction.MapStringInt_rend(self)
    def count(self, *args): return _CIntegrateAndFireTransferFunction.MapStringInt_count(self, *args)
    def erase(self, *args): return _CIntegrateAndFireTransferFunction.MapStringInt_erase(self, *args)
    def find(self, *args): return _CIntegrateAndFireTransferFunction.MapStringInt_find(self, *args)
    def lower_bound(self, *args): return _CIntegrateAndFireTransferFunction.MapStringInt_lower_bound(self, *args)
    def upper_bound(self, *args): return _CIntegrateAndFireTransferFunction.MapStringInt_upper_bound(self, *args)
    __swig_destroy__ = _CIntegrateAndFireTransferFunction.delete_MapStringInt
    __del__ = lambda self : None;
MapStringInt_swigregister = _CIntegrateAndFireTransferFunction.MapStringInt_swigregister
MapStringInt_swigregister(MapStringInt)

class MapStringString(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MapStringString, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MapStringString, name)
    __repr__ = _swig_repr
    def iterator(self): return _CIntegrateAndFireTransferFunction.MapStringString_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _CIntegrateAndFireTransferFunction.MapStringString___nonzero__(self)
    def __bool__(self): return _CIntegrateAndFireTransferFunction.MapStringString___bool__(self)
    def __len__(self): return _CIntegrateAndFireTransferFunction.MapStringString___len__(self)
    def __iter__(self): return self.key_iterator()
    def iterkeys(self): return self.key_iterator()
    def itervalues(self): return self.value_iterator()
    def iteritems(self): return self.iterator()
    def __getitem__(self, *args): return _CIntegrateAndFireTransferFunction.MapStringString___getitem__(self, *args)
    def __delitem__(self, *args): return _CIntegrateAndFireTransferFunction.MapStringString___delitem__(self, *args)
    def has_key(self, *args): return _CIntegrateAndFireTransferFunction.MapStringString_has_key(self, *args)
    def keys(self): return _CIntegrateAndFireTransferFunction.MapStringString_keys(self)
    def values(self): return _CIntegrateAndFireTransferFunction.MapStringString_values(self)
    def items(self): return _CIntegrateAndFireTransferFunction.MapStringString_items(self)
    def __contains__(self, *args): return _CIntegrateAndFireTransferFunction.MapStringString___contains__(self, *args)
    def key_iterator(self): return _CIntegrateAndFireTransferFunction.MapStringString_key_iterator(self)
    def value_iterator(self): return _CIntegrateAndFireTransferFunction.MapStringString_value_iterator(self)
    def __setitem__(self, *args): return _CIntegrateAndFireTransferFunction.MapStringString___setitem__(self, *args)
    def asdict(self): return _CIntegrateAndFireTransferFunction.MapStringString_asdict(self)
    def __init__(self, *args): 
        this = _CIntegrateAndFireTransferFunction.new_MapStringString(*args)
        try: self.this.append(this)
        except: self.this = this
    def empty(self): return _CIntegrateAndFireTransferFunction.MapStringString_empty(self)
    def size(self): return _CIntegrateAndFireTransferFunction.MapStringString_size(self)
    def clear(self): return _CIntegrateAndFireTransferFunction.MapStringString_clear(self)
    def swap(self, *args): return _CIntegrateAndFireTransferFunction.MapStringString_swap(self, *args)
    def get_allocator(self): return _CIntegrateAndFireTransferFunction.MapStringString_get_allocator(self)
    def begin(self): return _CIntegrateAndFireTransferFunction.MapStringString_begin(self)
    def end(self): return _CIntegrateAndFireTransferFunction.MapStringString_end(self)
    def rbegin(self): return _CIntegrateAndFireTransferFunction.MapStringString_rbegin(self)
    def rend(self): return _CIntegrateAndFireTransferFunction.MapStringString_rend(self)
    def count(self, *args): return _CIntegrateAndFireTransferFunction.MapStringString_count(self, *args)
    def erase(self, *args): return _CIntegrateAndFireTransferFunction.MapStringString_erase(self, *args)
    def find(self, *args): return _CIntegrateAndFireTransferFunction.MapStringString_find(self, *args)
    def lower_bound(self, *args): return _CIntegrateAndFireTransferFunction.MapStringString_lower_bound(self, *args)
    def upper_bound(self, *args): return _CIntegrateAndFireTransferFunction.MapStringString_upper_bound(self, *args)
    __swig_destroy__ = _CIntegrateAndFireTransferFunction.delete_MapStringString
    __del__ = lambda self : None;
MapStringString_swigregister = _CIntegrateAndFireTransferFunction.MapStringString_swigregister
MapStringString_swigregister(MapStringString)

class MapStringDouble(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MapStringDouble, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MapStringDouble, name)
    __repr__ = _swig_repr
    def iterator(self): return _CIntegrateAndFireTransferFunction.MapStringDouble_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _CIntegrateAndFireTransferFunction.MapStringDouble___nonzero__(self)
    def __bool__(self): return _CIntegrateAndFireTransferFunction.MapStringDouble___bool__(self)
    def __len__(self): return _CIntegrateAndFireTransferFunction.MapStringDouble___len__(self)
    def __iter__(self): return self.key_iterator()
    def iterkeys(self): return self.key_iterator()
    def itervalues(self): return self.value_iterator()
    def iteritems(self): return self.iterator()
    def __getitem__(self, *args): return _CIntegrateAndFireTransferFunction.MapStringDouble___getitem__(self, *args)
    def __delitem__(self, *args): return _CIntegrateAndFireTransferFunction.MapStringDouble___delitem__(self, *args)
    def has_key(self, *args): return _CIntegrateAndFireTransferFunction.MapStringDouble_has_key(self, *args)
    def keys(self): return _CIntegrateAndFireTransferFunction.MapStringDouble_keys(self)
    def values(self): return _CIntegrateAndFireTransferFunction.MapStringDouble_values(self)
    def items(self): return _CIntegrateAndFireTransferFunction.MapStringDouble_items(self)
    def __contains__(self, *args): return _CIntegrateAndFireTransferFunction.MapStringDouble___contains__(self, *args)
    def key_iterator(self): return _CIntegrateAndFireTransferFunction.MapStringDouble_key_iterator(self)
    def value_iterator(self): return _CIntegrateAndFireTransferFunction.MapStringDouble_value_iterator(self)
    def __setitem__(self, *args): return _CIntegrateAndFireTransferFunction.MapStringDouble___setitem__(self, *args)
    def asdict(self): return _CIntegrateAndFireTransferFunction.MapStringDouble_asdict(self)
    def __init__(self, *args): 
        this = _CIntegrateAndFireTransferFunction.new_MapStringDouble(*args)
        try: self.this.append(this)
        except: self.this = this
    def empty(self): return _CIntegrateAndFireTransferFunction.MapStringDouble_empty(self)
    def size(self): return _CIntegrateAndFireTransferFunction.MapStringDouble_size(self)
    def clear(self): return _CIntegrateAndFireTransferFunction.MapStringDouble_clear(self)
    def swap(self, *args): return _CIntegrateAndFireTransferFunction.MapStringDouble_swap(self, *args)
    def get_allocator(self): return _CIntegrateAndFireTransferFunction.MapStringDouble_get_allocator(self)
    def begin(self): return _CIntegrateAndFireTransferFunction.MapStringDouble_begin(self)
    def end(self): return _CIntegrateAndFireTransferFunction.MapStringDouble_end(self)
    def rbegin(self): return _CIntegrateAndFireTransferFunction.MapStringDouble_rbegin(self)
    def rend(self): return _CIntegrateAndFireTransferFunction.MapStringDouble_rend(self)
    def count(self, *args): return _CIntegrateAndFireTransferFunction.MapStringDouble_count(self, *args)
    def erase(self, *args): return _CIntegrateAndFireTransferFunction.MapStringDouble_erase(self, *args)
    def find(self, *args): return _CIntegrateAndFireTransferFunction.MapStringDouble_find(self, *args)
    def lower_bound(self, *args): return _CIntegrateAndFireTransferFunction.MapStringDouble_lower_bound(self, *args)
    def upper_bound(self, *args): return _CIntegrateAndFireTransferFunction.MapStringDouble_upper_bound(self, *args)
    __swig_destroy__ = _CIntegrateAndFireTransferFunction.delete_MapStringDouble
    __del__ = lambda self : None;
MapStringDouble_swigregister = _CIntegrateAndFireTransferFunction.MapStringDouble_swigregister
MapStringDouble_swigregister(MapStringDouble)

class MapStringComplexDouble(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MapStringComplexDouble, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MapStringComplexDouble, name)
    __repr__ = _swig_repr
    def iterator(self): return _CIntegrateAndFireTransferFunction.MapStringComplexDouble_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _CIntegrateAndFireTransferFunction.MapStringComplexDouble___nonzero__(self)
    def __bool__(self): return _CIntegrateAndFireTransferFunction.MapStringComplexDouble___bool__(self)
    def __len__(self): return _CIntegrateAndFireTransferFunction.MapStringComplexDouble___len__(self)
    def __iter__(self): return self.key_iterator()
    def iterkeys(self): return self.key_iterator()
    def itervalues(self): return self.value_iterator()
    def iteritems(self): return self.iterator()
    def __getitem__(self, *args): return _CIntegrateAndFireTransferFunction.MapStringComplexDouble___getitem__(self, *args)
    def __delitem__(self, *args): return _CIntegrateAndFireTransferFunction.MapStringComplexDouble___delitem__(self, *args)
    def has_key(self, *args): return _CIntegrateAndFireTransferFunction.MapStringComplexDouble_has_key(self, *args)
    def keys(self): return _CIntegrateAndFireTransferFunction.MapStringComplexDouble_keys(self)
    def values(self): return _CIntegrateAndFireTransferFunction.MapStringComplexDouble_values(self)
    def items(self): return _CIntegrateAndFireTransferFunction.MapStringComplexDouble_items(self)
    def __contains__(self, *args): return _CIntegrateAndFireTransferFunction.MapStringComplexDouble___contains__(self, *args)
    def key_iterator(self): return _CIntegrateAndFireTransferFunction.MapStringComplexDouble_key_iterator(self)
    def value_iterator(self): return _CIntegrateAndFireTransferFunction.MapStringComplexDouble_value_iterator(self)
    def __setitem__(self, *args): return _CIntegrateAndFireTransferFunction.MapStringComplexDouble___setitem__(self, *args)
    def asdict(self): return _CIntegrateAndFireTransferFunction.MapStringComplexDouble_asdict(self)
    def __init__(self, *args): 
        this = _CIntegrateAndFireTransferFunction.new_MapStringComplexDouble(*args)
        try: self.this.append(this)
        except: self.this = this
    def empty(self): return _CIntegrateAndFireTransferFunction.MapStringComplexDouble_empty(self)
    def size(self): return _CIntegrateAndFireTransferFunction.MapStringComplexDouble_size(self)
    def clear(self): return _CIntegrateAndFireTransferFunction.MapStringComplexDouble_clear(self)
    def swap(self, *args): return _CIntegrateAndFireTransferFunction.MapStringComplexDouble_swap(self, *args)
    def get_allocator(self): return _CIntegrateAndFireTransferFunction.MapStringComplexDouble_get_allocator(self)
    def begin(self): return _CIntegrateAndFireTransferFunction.MapStringComplexDouble_begin(self)
    def end(self): return _CIntegrateAndFireTransferFunction.MapStringComplexDouble_end(self)
    def rbegin(self): return _CIntegrateAndFireTransferFunction.MapStringComplexDouble_rbegin(self)
    def rend(self): return _CIntegrateAndFireTransferFunction.MapStringComplexDouble_rend(self)
    def count(self, *args): return _CIntegrateAndFireTransferFunction.MapStringComplexDouble_count(self, *args)
    def erase(self, *args): return _CIntegrateAndFireTransferFunction.MapStringComplexDouble_erase(self, *args)
    def find(self, *args): return _CIntegrateAndFireTransferFunction.MapStringComplexDouble_find(self, *args)
    def lower_bound(self, *args): return _CIntegrateAndFireTransferFunction.MapStringComplexDouble_lower_bound(self, *args)
    def upper_bound(self, *args): return _CIntegrateAndFireTransferFunction.MapStringComplexDouble_upper_bound(self, *args)
    __swig_destroy__ = _CIntegrateAndFireTransferFunction.delete_MapStringComplexDouble
    __del__ = lambda self : None;
MapStringComplexDouble_swigregister = _CIntegrateAndFireTransferFunction.MapStringComplexDouble_swigregister
MapStringComplexDouble_swigregister(MapStringComplexDouble)

class CToolClass(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, CToolClass, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, CToolClass, name)
    __repr__ = _swig_repr
    __swig_setmethods__["DoubleDict"] = _CIntegrateAndFireTransferFunction.CToolClass_DoubleDict_set
    __swig_getmethods__["DoubleDict"] = _CIntegrateAndFireTransferFunction.CToolClass_DoubleDict_get
    if _newclass:DoubleDict = _swig_property(_CIntegrateAndFireTransferFunction.CToolClass_DoubleDict_get, _CIntegrateAndFireTransferFunction.CToolClass_DoubleDict_set)
    __swig_setmethods__["IntDict"] = _CIntegrateAndFireTransferFunction.CToolClass_IntDict_set
    __swig_getmethods__["IntDict"] = _CIntegrateAndFireTransferFunction.CToolClass_IntDict_get
    if _newclass:IntDict = _swig_property(_CIntegrateAndFireTransferFunction.CToolClass_IntDict_get, _CIntegrateAndFireTransferFunction.CToolClass_IntDict_set)
    __swig_setmethods__["StringDict"] = _CIntegrateAndFireTransferFunction.CToolClass_StringDict_set
    __swig_getmethods__["StringDict"] = _CIntegrateAndFireTransferFunction.CToolClass_StringDict_get
    if _newclass:StringDict = _swig_property(_CIntegrateAndFireTransferFunction.CToolClass_StringDict_get, _CIntegrateAndFireTransferFunction.CToolClass_StringDict_set)
    def setDicts(self, *args): return _CIntegrateAndFireTransferFunction.CToolClass_setDicts(self, *args)
    def __init__(self): 
        this = _CIntegrateAndFireTransferFunction.new_CToolClass()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _CIntegrateAndFireTransferFunction.delete_CToolClass
    __del__ = lambda self : None;
CToolClass_swigregister = _CIntegrateAndFireTransferFunction.CToolClass_swigregister
CToolClass_swigregister(CToolClass)


def getComplex(*args):
  return _CIntegrateAndFireTransferFunction.getComplex(*args)
getComplex = _CIntegrateAndFireTransferFunction.getComplex

def openFile(*args):
  return _CIntegrateAndFireTransferFunction.openFile(*args)
openFile = _CIntegrateAndFireTransferFunction.openFile

def closeFile(*args):
  return _CIntegrateAndFireTransferFunction.closeFile(*args)
closeFile = _CIntegrateAndFireTransferFunction.closeFile

def getWord(*args):
  return _CIntegrateAndFireTransferFunction.getWord(*args)
getWord = _CIntegrateAndFireTransferFunction.getWord

def readUntilLineEnd(*args):
  return _CIntegrateAndFireTransferFunction.readUntilLineEnd(*args)
readUntilLineEnd = _CIntegrateAndFireTransferFunction.readUntilLineEnd

def readUntilFileEnd(*args):
  return _CIntegrateAndFireTransferFunction.readUntilFileEnd(*args)
readUntilFileEnd = _CIntegrateAndFireTransferFunction.readUntilFileEnd

def getLinesStart(*args):
  return _CIntegrateAndFireTransferFunction.getLinesStart(*args)
getLinesStart = _CIntegrateAndFireTransferFunction.getLinesStart

def goToLine(*args):
  return _CIntegrateAndFireTransferFunction.goToLine(*args)
goToLine = _CIntegrateAndFireTransferFunction.goToLine

def goToLastLine(*args):
  return _CIntegrateAndFireTransferFunction.goToLastLine(*args)
goToLastLine = _CIntegrateAndFireTransferFunction.goToLastLine

def getNLines(*args):
  return _CIntegrateAndFireTransferFunction.getNLines(*args)
getNLines = _CIntegrateAndFireTransferFunction.getNLines

def updateRanSeed(*args):
  return _CIntegrateAndFireTransferFunction.updateRanSeed(*args)
updateRanSeed = _CIntegrateAndFireTransferFunction.updateRanSeed

def ran1(*args):
  return _CIntegrateAndFireTransferFunction.ran1(*args)
ran1 = _CIntegrateAndFireTransferFunction.ran1

def gasdev(*args):
  return _CIntegrateAndFireTransferFunction.gasdev(*args)
gasdev = _CIntegrateAndFireTransferFunction.gasdev

def expdev(*args):
  return _CIntegrateAndFireTransferFunction.expdev(*args)
expdev = _CIntegrateAndFireTransferFunction.expdev

def gamdev(*args):
  return _CIntegrateAndFireTransferFunction.gamdev(*args)
gamdev = _CIntegrateAndFireTransferFunction.gamdev

def factorial(*args):
  return _CIntegrateAndFireTransferFunction.factorial(*args)
factorial = _CIntegrateAndFireTransferFunction.factorial

def arrangement(*args):
  return _CIntegrateAndFireTransferFunction.arrangement(*args)
arrangement = _CIntegrateAndFireTransferFunction.arrangement

def combinaison(*args):
  return _CIntegrateAndFireTransferFunction.combinaison(*args)
combinaison = _CIntegrateAndFireTransferFunction.combinaison

def printVecFloat(*args):
  return _CIntegrateAndFireTransferFunction.printVecFloat(*args)
printVecFloat = _CIntegrateAndFireTransferFunction.printVecFloat

def printVecInt(*args):
  return _CIntegrateAndFireTransferFunction.printVecInt(*args)
printVecInt = _CIntegrateAndFireTransferFunction.printVecInt

def printArrayFloat(*args):
  return _CIntegrateAndFireTransferFunction.printArrayFloat(*args)
printArrayFloat = _CIntegrateAndFireTransferFunction.printArrayFloat

def printArrayInt(*args):
  return _CIntegrateAndFireTransferFunction.printArrayInt(*args)
printArrayInt = _CIntegrateAndFireTransferFunction.printArrayInt
class isEqualValue(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, isEqualValue, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, isEqualValue, name)
    __repr__ = _swig_repr
    def __init__(self, _value=0): 
        this = _CIntegrateAndFireTransferFunction.new_isEqualValue(_value)
        try: self.this.append(this)
        except: self.this = this
    def __call__(self, *args): return _CIntegrateAndFireTransferFunction.isEqualValue___call__(self, *args)
    __swig_destroy__ = _CIntegrateAndFireTransferFunction.delete_isEqualValue
    __del__ = lambda self : None;
isEqualValue_swigregister = _CIntegrateAndFireTransferFunction.isEqualValue_swigregister
isEqualValue_swigregister(isEqualValue)

class isEven(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, isEven, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, isEven, name)
    __repr__ = _swig_repr
    def __call__(self, *args): return _CIntegrateAndFireTransferFunction.isEven___call__(self, *args)
    def __init__(self): 
        this = _CIntegrateAndFireTransferFunction.new_isEven()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _CIntegrateAndFireTransferFunction.delete_isEven
    __del__ = lambda self : None;
isEven_swigregister = _CIntegrateAndFireTransferFunction.isEven_swigregister
isEven_swigregister(isEven)

class isOdd(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, isOdd, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, isOdd, name)
    __repr__ = _swig_repr
    def __call__(self, *args): return _CIntegrateAndFireTransferFunction.isOdd___call__(self, *args)
    def __init__(self): 
        this = _CIntegrateAndFireTransferFunction.new_isOdd()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _CIntegrateAndFireTransferFunction.delete_isOdd
    __del__ = lambda self : None;
isOdd_swigregister = _CIntegrateAndFireTransferFunction.isOdd_swigregister
isOdd_swigregister(isOdd)

class meanClass(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, meanClass, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, meanClass, name)
    __repr__ = _swig_repr
    def __init__(self, _vecSize=0): 
        this = _CIntegrateAndFireTransferFunction.new_meanClass(_vecSize)
        try: self.this.append(this)
        except: self.this = this
    __swig_setmethods__["meanValue"] = _CIntegrateAndFireTransferFunction.meanClass_meanValue_set
    __swig_getmethods__["meanValue"] = _CIntegrateAndFireTransferFunction.meanClass_meanValue_get
    if _newclass:meanValue = _swig_property(_CIntegrateAndFireTransferFunction.meanClass_meanValue_get, _CIntegrateAndFireTransferFunction.meanClass_meanValue_set)
    __swig_setmethods__["vecSize"] = _CIntegrateAndFireTransferFunction.meanClass_vecSize_set
    __swig_getmethods__["vecSize"] = _CIntegrateAndFireTransferFunction.meanClass_vecSize_get
    if _newclass:vecSize = _swig_property(_CIntegrateAndFireTransferFunction.meanClass_vecSize_get, _CIntegrateAndFireTransferFunction.meanClass_vecSize_set)
    def __call__(self, *args): return _CIntegrateAndFireTransferFunction.meanClass___call__(self, *args)
    __swig_destroy__ = _CIntegrateAndFireTransferFunction.delete_meanClass
    __del__ = lambda self : None;
meanClass_swigregister = _CIntegrateAndFireTransferFunction.meanClass_swigregister
meanClass_swigregister(meanClass)


def meanValue(*args):
  return _CIntegrateAndFireTransferFunction.meanValue(*args)
meanValue = _CIntegrateAndFireTransferFunction.meanValue

def stdValue(*args):
  return _CIntegrateAndFireTransferFunction.stdValue(*args)
stdValue = _CIntegrateAndFireTransferFunction.stdValue

def meanVec(*args):
  return _CIntegrateAndFireTransferFunction.meanVec(*args)
meanVec = _CIntegrateAndFireTransferFunction.meanVec

def stdVec(*args):
  return _CIntegrateAndFireTransferFunction.stdVec(*args)
stdVec = _CIntegrateAndFireTransferFunction.stdVec

def findAll_whereValue(*args):
  return _CIntegrateAndFireTransferFunction.findAll_whereValue(*args)
findAll_whereValue = _CIntegrateAndFireTransferFunction.findAll_whereValue

def findAll_even(*args):
  return _CIntegrateAndFireTransferFunction.findAll_even(*args)
findAll_even = _CIntegrateAndFireTransferFunction.findAll_even

def getPermutations(*args):
  return _CIntegrateAndFireTransferFunction.getPermutations(*args)
getPermutations = _CIntegrateAndFireTransferFunction.getPermutations

def getRowFromVecVec(*args):
  return _CIntegrateAndFireTransferFunction.getRowFromVecVec(*args)
getRowFromVecVec = _CIntegrateAndFireTransferFunction.getRowFromVecVec

def getColFromVecVec(*args):
  return _CIntegrateAndFireTransferFunction.getColFromVecVec(*args)
getColFromVecVec = _CIntegrateAndFireTransferFunction.getColFromVecVec

def getRowsFromVecVec(*args):
  return _CIntegrateAndFireTransferFunction.getRowsFromVecVec(*args)
getRowsFromVecVec = _CIntegrateAndFireTransferFunction.getRowsFromVecVec

def getVecVecFromVecVec(*args):
  return _CIntegrateAndFireTransferFunction.getVecVecFromVecVec(*args)
getVecVecFromVecVec = _CIntegrateAndFireTransferFunction.getVecVecFromVecVec

def getCombinaisons(*args):
  return _CIntegrateAndFireTransferFunction.getCombinaisons(*args)
getCombinaisons = _CIntegrateAndFireTransferFunction.getCombinaisons

def whichIndx(*args):
  return _CIntegrateAndFireTransferFunction.whichIndx(*args)
whichIndx = _CIntegrateAndFireTransferFunction.whichIndx

def vecSub(*args):
  return _CIntegrateAndFireTransferFunction.vecSub(*args)
vecSub = _CIntegrateAndFireTransferFunction.vecSub

def vecFromSub(*args):
  return _CIntegrateAndFireTransferFunction.vecFromSub(*args)
vecFromSub = _CIntegrateAndFireTransferFunction.vecFromSub

def vecMul(*args):
  return _CIntegrateAndFireTransferFunction.vecMul(*args)
vecMul = _CIntegrateAndFireTransferFunction.vecMul

def vecVecAdd(*args):
  return _CIntegrateAndFireTransferFunction.vecVecAdd(*args)
vecVecAdd = _CIntegrateAndFireTransferFunction.vecVecAdd

def range(*args):
  return _CIntegrateAndFireTransferFunction.range(*args)
range = _CIntegrateAndFireTransferFunction.range

def arange(*args):
  return _CIntegrateAndFireTransferFunction.arange(*args)
arange = _CIntegrateAndFireTransferFunction.arange

def vecOnes(*args):
  return _CIntegrateAndFireTransferFunction.vecOnes(*args)
vecOnes = _CIntegrateAndFireTransferFunction.vecOnes

def vecZeros(*args):
  return _CIntegrateAndFireTransferFunction.vecZeros(*args)
vecZeros = _CIntegrateAndFireTransferFunction.vecZeros

def vecVecOnes(*args):
  return _CIntegrateAndFireTransferFunction.vecVecOnes(*args)
vecVecOnes = _CIntegrateAndFireTransferFunction.vecVecOnes

def vecVecZeros(*args):
  return _CIntegrateAndFireTransferFunction.vecVecZeros(*args)
vecVecZeros = _CIntegrateAndFireTransferFunction.vecVecZeros
class CIntegrateAndFireTransferFunctionClass(CToolClass):
    __swig_setmethods__ = {}
    for _s in [CToolClass]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, CIntegrateAndFireTransferFunctionClass, name, value)
    __swig_getmethods__ = {}
    for _s in [CToolClass]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, CIntegrateAndFireTransferFunctionClass, name)
    __repr__ = _swig_repr
    def computeIntegralUpperBound(self): return _CIntegrateAndFireTransferFunction.CIntegrateAndFireTransferFunctionClass_computeIntegralUpperBound(self)
    def computeIntegralLowerBound(self): return _CIntegrateAndFireTransferFunction.CIntegrateAndFireTransferFunctionClass_computeIntegralLowerBound(self)
    def getErrorFunction(self, *args): return _CIntegrateAndFireTransferFunction.CIntegrateAndFireTransferFunctionClass_getErrorFunction(self, *args)
    def getLIFStationaryRate(self): return _CIntegrateAndFireTransferFunction.CIntegrateAndFireTransferFunctionClass_getLIFStationaryRate(self)
    def getRatePerturbativeRate(self, *args): return _CIntegrateAndFireTransferFunction.CIntegrateAndFireTransferFunctionClass_getRatePerturbativeRate(self, *args)
    def getLIFPerturbativeRate0(self): return _CIntegrateAndFireTransferFunction.CIntegrateAndFireTransferFunctionClass_getLIFPerturbativeRate0(self)
    def gsurg(self, *args): return _CIntegrateAndFireTransferFunction.CIntegrateAndFireTransferFunctionClass_gsurg(self, *args)
    def onefone(self, *args): return _CIntegrateAndFireTransferFunction.CIntegrateAndFireTransferFunctionClass_onefone(self, *args)
    def correctionlargey(self, *args): return _CIntegrateAndFireTransferFunction.CIntegrateAndFireTransferFunctionClass_correctionlargey(self, *args)
    def u01(self, *args): return _CIntegrateAndFireTransferFunction.CIntegrateAndFireTransferFunctionClass_u01(self, *args)
    def u23(self, *args): return _CIntegrateAndFireTransferFunction.CIntegrateAndFireTransferFunctionClass_u23(self, *args)
    def getBrunelLIFPerturbativeRate(self, *args): return _CIntegrateAndFireTransferFunction.CIntegrateAndFireTransferFunctionClass_getBrunelLIFPerturbativeRate(self, *args)
    def inside_integ(self, *args): return _CIntegrateAndFireTransferFunction.CIntegrateAndFireTransferFunctionClass_inside_integ(self, *args)
    __swig_setmethods__["deriv"] = _CIntegrateAndFireTransferFunction.CIntegrateAndFireTransferFunctionClass_deriv_set
    __swig_getmethods__["deriv"] = _CIntegrateAndFireTransferFunction.CIntegrateAndFireTransferFunctionClass_deriv_get
    if _newclass:deriv = _swig_property(_CIntegrateAndFireTransferFunction.CIntegrateAndFireTransferFunctionClass_deriv_get, _CIntegrateAndFireTransferFunction.CIntegrateAndFireTransferFunctionClass_deriv_set)
    def phi_derivs(self, *args): return _CIntegrateAndFireTransferFunction.CIntegrateAndFireTransferFunctionClass_phi_derivs(self, *args)
    def phi_t_derivs(self, *args): return _CIntegrateAndFireTransferFunction.CIntegrateAndFireTransferFunctionClass_phi_t_derivs(self, *args)
    def rkck(self, *args): return _CIntegrateAndFireTransferFunction.CIntegrateAndFireTransferFunctionClass_rkck(self, *args)
    def rkqs(self, *args): return _CIntegrateAndFireTransferFunction.CIntegrateAndFireTransferFunctionClass_rkqs(self, *args)
    def odeint(self, *args): return _CIntegrateAndFireTransferFunction.CIntegrateAndFireTransferFunctionClass_odeint(self, *args)
    def phi_t_rka(self, *args): return _CIntegrateAndFireTransferFunction.CIntegrateAndFireTransferFunctionClass_phi_t_rka(self, *args)
    def getHakimLIFPerturbativeRate(self, *args): return _CIntegrateAndFireTransferFunction.CIntegrateAndFireTransferFunctionClass_getHakimLIFPerturbativeRate(self, *args)
    def __init__(self): 
        this = _CIntegrateAndFireTransferFunction.new_CIntegrateAndFireTransferFunctionClass()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _CIntegrateAndFireTransferFunction.delete_CIntegrateAndFireTransferFunctionClass
    __del__ = lambda self : None;
CIntegrateAndFireTransferFunctionClass_swigregister = _CIntegrateAndFireTransferFunction.CIntegrateAndFireTransferFunctionClass_swigregister
CIntegrateAndFireTransferFunctionClass_swigregister(CIntegrateAndFireTransferFunctionClass)

# This file is compatible with both classic and new-style classes.


